apiVersion: apps/v1
kind: Deployment  #Need to try by changing this value to 'Pod'
metadata:
  name: docker-k8s-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-k8s-demo
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: docker-k8s-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /liveness # Path to the health endpoint
              port: 8080    # Port where the application listens
            initialDelaySeconds: 15 # Delay before the first probe
            periodSeconds: 10     # How often to perform the probe
            timeoutSeconds: 1     # Timeout for the probe
            failureThreshold: 3   # Number of failures before restart
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /startUp
              port: 8080
            failureThreshold: 30
            periodSeconds: 10