apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-demo
spec:
  selector:
    matchLabels:
      app: docker-k8s-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: docker-k8s-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080