apiVersion: v1
kind: Service
metadata:
  name: docker-k8s-demo-service
spec:
  selector:
    app: docker-k8s-demo
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort